### ISSUE TITLE
#include <stdlib.h>: Error

### ISSUE THREAD

**Issue by ArielAbreu** [gasman/bonsai-c#4]
When trying to parse a C file with stdlib.h included I get this error:

```
/Users/.../git/bonsai-c/parser.js:322
        throw new Error(str);
              ^
Error: Parse error on line 1:
#include <stdio.h>int main
---------^
Expecting '(', ')', '[', ',', ':', '=', ';', 'TYPEDEF', 'EXTERN', 'STATIC', 'AUTO', 'REGISTER', 'VOID', 'CHAR', 'SHORT', 'INT', 'LONG', 'FLOAT', 'DOUBLE', 'SIGNED', 'UNSIGNED', 'TYPE_NAME', '{', 'STRUCT', 'UNION', 'ENUM', 'CONST', 'VOLATILE', got '<'
    at Object.parseError (/Users/.../git/bonsai-c/parser.js:322:15)
    at Object.parse (/Users/.../git/bonsai-c/parser.js:387:22)
    at Object.exports.main (/Users/.../git/bonsai-c/bonsai-c.js:20:21)
    at Object.<anonymous> (/Users/.../git/bonsai-c/bonsai-c.js:37:10)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Function.Module.runMain (module.js:469:10)
    at startup (node.js:117:18)
```

With the newest commit (that's supposed to include '<' and '>', right?).

My file:
```c
#include <stdio.h>

int main() {
  printf("foo");
}
```

**Comment by gasman** [comment]
The latest commits only add '<' and '>' as comparison operators (e.g. `if (i < 3)`), not for other purposes.

I'll close this ticket, as this project is really too early in development to have tickets for missing features (otherwise there will be hundreds of them...)

**Comment by ArielAbreu** [comment]
Ok, thanks. I'll fork this project and try and add a preprocessor.
