### ISSUE TITLE
Basic Hello World Fails

### ISSUE THREAD

**Issue by zz85** [gasman/bonsai-c#6]
```c
/* Hello World program */

#include<stdio.h>

main()
{
    printf("Hello World");

}
```

output
```
node bonsai-c.js hello.c

/Users/joshua/dev/wip/synth/bonsai-c/parser.js:802
case 0: comment();
        ^
ReferenceError: comment is not defined
    at Object.anonymous [as performAction] (/Users/joshua/dev/wip/synth/bonsai-c/parser.js:802:9)
    at Object.lexer.test_match (/Users/joshua/dev/wip/synth/bonsai-c/parser.js:671:36)
    at Object.lexer.next (/Users/joshua/dev/wip/synth/bonsai-c/parser.js:727:26)
    at Object.lex (/Users/joshua/dev/wip/synth/bonsai-c/parser.js:747:22)
    at lex (/Users/joshua/dev/wip/synth/bonsai-c/parser.js:369:27)
    at Object.parse (/Users/joshua/dev/wip/synth/bonsai-c/parser.js:382:26)
    at Object.exports.main (/Users/joshua/dev/wip/synth/bonsai-c/bonsai-c.js:20:21)
    at Object.<anonymous> (/Users/joshua/dev/wip/synth/bonsai-c/bonsai-c.js:37:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by zz85** [comment]
perhaps i'm getting ahead of myself too early. the files in `/tests` works except for `/tests/calc.js`

**Comment by gasman** [comment]
Yes, this is expected at the moment. At this point, the purpose of bonsai-c is best described as "making the language features of asm.js available in a language that humans can write". The Hello World program relies on strings and the C standard library, which are outside of asm.js's capabilities. We may support these in future, but it's not a priority - string handling is something that asm.js is simply not designed for.
